### ISSUE TITLE
Universal resolver raw method data

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/context#3]
In order to make these tests fair, we need to ensure that the UR is not dropping properties, or doing any parsing of the JSON LD for these tests. 

We should be getting JSON as it comes from the method resolver, with no modifications at all.

Some of these errors are UR exploding trying to handle linked data contexts: 
https://travis-ci.org/decentralized-identity/context/builds/642227864#L285

Others are just UR test identifiers that don't even resolve.

@peacekeeper interested to hear your thoughts on getting the raw resolver data directly for testing compatibility.

**Comment by gjgd** [comment]
+1 for the possibility to get the raw pre JSON-LD processing JSON from the method driver

**Comment by OR13** [comment]
I'm implemented a local caching layer which allows you to bipass the universal resolver for dids that don't currently resolve because of jsonld issues.

**Comment by OR13** [comment]
this also saves the UR from our test spam.
